### ISSUE TITLE
Default shortcuts use keys used in most programs.

### ISSUE THREAD

**Issue by adderly** [holmeslinux/Manjaro-JWM#4]
By default, this provides Control+keys bindings and Alt+keys bindings which are used in most programs.
Example: Control+f is defined to open File manager, most programs use this as a search keyword, preferably Super should be used instead for most shortcuts.

**Comment by blconde** [comment]
And what do you mean with this 'by default': JWM's default?
Anyhow, yes, we changed a little the shortcuts, but we tried to match other majors distros/WM. Here you can find our user guide https://github.com/holmeslinux/Manjaro-JWM/tree/master/User%20Orientation%20Guide , where we explain all the shortcuts (note: still isnt the final version of the guide, but its more than 90% done, so can be pretty helpfull; and it will be shipped with Manjaro JWM).

**Comment by adderly** [comment]
@blconde Nice, i see you changed control + binds which was a silly thing to have. I Hope that a gui tool is develop to tackle all of this configurations in files.
 :dancer:

**Comment by blconde** [comment]
Yep, sometimes it is a matter of  decision making: if you choose the path x, maybe you're not gonna be able to reach the path y... and I guess we're trying to bring a more or less familiar shortcuts. But you're free to edit and assigned whatever you want (of course, ehehe).

And being honest, at least to me, I dont see the need for a gui tool to assign shortcuts, because it is pretty simple to open a config file like ~/.jwm/keys in a text editor and edit there yourself. And an important point of Manjaro JWM (and JWM itself) is to be tight, light and simple.

Finally, we're working on JWMConf, a simple tool that approaches this situation, but with a slight different point of view: it concentrates a bunch of configurable stuff in Manjaro JWM and when you choose a option it opens the exact config file in a appropriate text editor. I guess this helps a lot and it is handy.
