### ISSUE TITLE
Dunst key binds are registered globally, no matter if it is not active/focused.

### ISSUE THREAD

**Issue by adderly** [holmeslinux/Manjaro-JWM#5]
This is a real drag, by default dunst gets assigned control+w. Is that really a good thing? There should be another way for sending this types of actions to this applications. Only when they get focus.

How can that be achieved?

**Comment by blconde** [comment]
Hi there @adderly , I'm helping @holmeslinux in testing and stuff in Manjaro JWM and we decided to disable this 'ctrl+w' shortcut in Dunst because it was causing conflicts in other programs (as Pale Moon and PCManFM, to close tabs; here: https://forum.manjaro.org/index.php?topic=30486.msg252692#msg252692 ).
But you are saying that you'd like this function back, maybe using another shortcut, is this it?
Anyway, you can go to the ~/.config/dunst/dunstrc file and take a look, maybe assign the shortcut is fits better to you.

**Comment by adderly** [comment]
@blconde  No, i was saying it shouldn't be there. I installed my system couple of weeks ago, i suppose this modifications will come in the next iso.

**Comment by blconde** [comment]
Ah, now I see. But what version have you tried,15.12? You can use the latest 16 dev version, number 8216, here: https://forum.manjaro.org/index.php?topic=30913.0 , that uses Manjaro stable repos and it is pretty much polished.

Now we're working mostly in some menus placement, tiny configuration stuff, documentation, very few issues left to solve, because for the stable release we hope to deliver as much as possible a flawless Manjaro JWM.

**Comment by holmeslinux** [comment]
tomorrow i release another test version!

vlw fwi, Holmes :)
